// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBKHKjlcOP_s9aQYLNmffU6vsbpdbZMy8M',
    appId: '1:388190316633:web:924d29f8b16dd4d3fba948',
    messagingSenderId: '388190316633',
    projectId: 'instagram-clone-34eae',
    authDomain: 'instagram-clone-34eae.firebaseapp.com',
    storageBucket: 'instagram-clone-34eae.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWlWFmntvu4ufLDkW4CCoQNKg-4XWpifs',
    appId: '1:388190316633:android:0d593ce3e95bcc82fba948',
    messagingSenderId: '388190316633',
    projectId: 'instagram-clone-34eae',
    storageBucket: 'instagram-clone-34eae.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhFDOFBiCqDZh6jhOZMF1n6SwJ3VHEVc4',
    appId: '1:388190316633:ios:6e0dedc6cd5db49bfba948',
    messagingSenderId: '388190316633',
    projectId: 'instagram-clone-34eae',
    storageBucket: 'instagram-clone-34eae.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhFDOFBiCqDZh6jhOZMF1n6SwJ3VHEVc4',
    appId: '1:388190316633:ios:6e0dedc6cd5db49bfba948',
    messagingSenderId: '388190316633',
    projectId: 'instagram-clone-34eae',
    storageBucket: 'instagram-clone-34eae.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBKHKjlcOP_s9aQYLNmffU6vsbpdbZMy8M',
    appId: '1:388190316633:web:f0ca0a4a813cab5bfba948',
    messagingSenderId: '388190316633',
    projectId: 'instagram-clone-34eae',
    authDomain: 'instagram-clone-34eae.firebaseapp.com',
    storageBucket: 'instagram-clone-34eae.appspot.com',
  );

}